spring:
  kafka:
    bootstrap-servers:
      - ${env.kafka.bootstrap.host}:9092
    consumer:
      group-id: ${kafka.reservation-topic.consumer-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  reservation-topic:
    name: parking-spot-reserved
    consumer-group: user-service-consumer
    partitions-count: 1
    replication-factor: 1
